/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Analyzes JavaScript/TypeScript source code and returns JSON AST analysis result
 *
 * # Arguments
 * * `source` - The source code to analyze
 *
 * # Returns
 * * JSON string containing exports and linting issues
 */
export declare function analyzeAst(source: string): string
