/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class ProjectGraph {
  add_file(path: string, code: string): void
  get_file_structure(path: string): string | null
  get_symbol_details(symbol: string): Array<string>
  analyze_dependencies(paths: Array<string>): string
}

/**
 * Analyzes JavaScript/TypeScript source code and returns JSON AST analysis result
 *
 * # Arguments
 * * `source` - The source code to analyze
 *
 * # Returns
 * * JSON string containing exports and linting issues
 */
export declare function analyze_ast(source: string): string

export declare function apply_rule(source: string, yamlRule: string): string

export declare function find_pattern(source: string, pattern: string): string

export declare function find_pattern_in_vue_sfc(source: string, pattern: string): string

export declare function initialize_graph(mode: string): ProjectGraph

export declare function scan_directory(rootPath: string, yamlRule: string, dryRun: boolean): string
