/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function initialize_graph(mode: string): ProjectGraph
/**
 * Analyzes JavaScript/TypeScript source code and returns JSON AST analysis result
 *
 * # Arguments
 * * `source` - The source code to analyze
 *
 * # Returns
 * * JSON string containing exports and linting issues
 */
export declare function analyzeAst(source: string): string
export declare function findPattern(source: string, pattern: string): string
export declare function findPatternInVueSfc(source: string, pattern: string): string
export declare function applyRule(source: string, yamlRule: string): string
export declare function scanDirectory(rootPath: string, yamlRule: string, dryRun: boolean): string
export declare class ProjectGraph {
  add_file(path: string, code: string): void
  get_file_structure(path: string): string | null
  get_symbol_details(symbol: string): Array<string>
  analyze_dependencies(paths: Array<string>): string
}
